### PR TITLE
Add description about the folder purposes in project structure.

### PR DESCRIPTION
**Pull request by andriyun**
Please read carefully each line b/c this instruction should define project growing way and strategy

Feel free to ask/add comments

### CODE REVIEW

**Comment by franzskaaning** [comment]
Reviewed :)

**Comment by andriyun** [comment]
Any news about the review?
@skifter @stanbellcom @dsbellcom I'm looking forward to your opinion :)

This rules and changes just give us the small improvement to keep features and code in order in some order regarding file structure.
But not fix all problems
As I see right now we have a lot of overrides in new project related to new changes.

**Comment by andriyun** [comment]
BTW in case you are agree with proposition mark your review as approved ;)

**Review by skifter — APPROVED** [review]
As it is an improved way of what we intended to do. I approve. :-)

**Pull request merged**
